on:
  pull_request:
    branches:
      - main
      - master

  push:
    branches:
      - main
      - master
      - develop

name: "Build and Release"
jobs:
  build:

    name: "create android build"
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion

      - name: Create new file without newline char from version.txt
        run: tr -d '\n' < version.txt > version1.txt

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version1.txt

      - name: Update version in YAML
        run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml
        

    name: "Build and release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          cache: 'gradle'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0'
          cache: true

      - run: flutter pub get
      #- run: flutter analyze .
      - run: flutter build apk

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk